import type { Tier } from "./tier";

export type StyleCategory = "casual" | "print" | "cursive" | "marker" | "elegant";

export interface StyleEntry {
  /** URL-safe id, stable forever: saved documents reference it. */
  id: string;
  /** Display name. */
  name: string;
  /** One line on how the hand looks and when to use it. */
  blurb: string;
  category: StyleCategory;
  tier: Tier;
  /** Font file, relative to assets/fonts. */
  font: { dir: string; file: string; family: string; designer: string; license: "OFL" | "Apache-2.0" };
  /** Scripts beyond basic Latin that the font covers. */
  scripts: ("latin-ext" | "cyrillic" | "greek" | "vietnamese")[];
  /** Joined script: letters connect, so per-letter jitter is disabled. */
  connected: boolean;
  /** Per-font calibration so every style sits on the line at a similar size. */
  tune: {
    sizeAdjust: number;
    weight: number;
    slant: number;
    tracking: number;
    wordSpace: number;
    baselineShift: number;
  };
}

const t = (tune: Partial<StyleEntry["tune"]> = {}): StyleEntry["tune"] => ({
  sizeAdjust: 1,
  weight: 1,
  slant: 0,
  tracking: 0,
  wordSpace: 1,
  baselineShift: 0,
  ...tune,
});

export const STYLES: StyleEntry[] = [
  /* ------------------------------ Free ------------------------------ */
  {
    id: "mira",
    name: "Mira",
    blurb: "Quick, rounded and a little slanted. The hand most people write notes in.",
    category: "print",
    tier: "free",
    font: { dir: "caveat", file: "Caveat[wght].ttf", family: "Caveat", designer: "Impallari Type", license: "OFL" },
    scripts: ["latin-ext", "cyrillic"],
    connected: false,
    tune: t({ weight: 0.9 }),
  },
  {
    id: "ansel",
    name: "Ansel",
    blurb: "Relaxed, wide print with long ascenders. Reads like someone who takes their time.",
    category: "print",
    tier: "free",
    font: { dir: "nothingyoucoulddo", file: "NothingYouCouldDo.ttf", family: "Nothing You Could Do", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t(),
  },
  {
    id: "theo",
    name: "Theo",
    blurb: "Tidy, upright print. The careful student in the front row.",
    category: "print",
    tier: "free",
    font: { dir: "patrickhand", file: "PatrickHand-Regular.ttf", family: "Patrick Hand", designer: "Patrick Wagesreiter", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: false,
    tune: t({ weight: 0.4 }),
  },
  {
    id: "kit",
    name: "Kit",
    blurb: "Fast, spiky scrawl. The night-before-the-deadline hand.",
    category: "print",
    tier: "free",
    font: { dir: "reeniebeanie", file: "ReenieBeanie.ttf", family: "Reenie Beanie", designer: "James Grieshaber", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t(),
  },
  {
    id: "june",
    name: "June",
    blurb: "Tall, narrow and airy. Fits a lot on a line without looking cramped.",
    category: "print",
    tier: "free",
    font: { dir: "shadowsintolighttwo", file: "ShadowsIntoLightTwo-Regular.ttf", family: "Shadows Into Light Two", designer: "Kimberly Geswein", license: "OFL" },
    scripts: ["latin-ext"],
    connected: false,
    tune: t({ sizeAdjust: 1.08 }),
  },
  {
    id: "wren",
    name: "Wren",
    blurb: "Thin and light, written with barely any pressure.",
    category: "print",
    tier: "free",
    font: { dir: "waitingforthesunrise", file: "WaitingfortheSunrise.ttf", family: "Waiting for the Sunrise", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ weight: 1.2 }),
  },
  {
    id: "ada",
    name: "Ada",
    blurb: "Architect's lettering: small caps feel, even strokes, drafted with a fine liner.",
    category: "print",
    tier: "free",
    font: { dir: "architectsdaughter", file: "ArchitectsDaughter-Regular.ttf", family: "Architects Daughter", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 0.88, weight: 0.7 }),
  },
  {
    id: "noor",
    name: "Noor",
    blurb: "Natural and rounded with an easy rhythm. Also writes Greek.",
    category: "print",
    tier: "free",
    font: { dir: "mynerve", file: "Mynerve-Regular.ttf", family: "Mynerve", designer: "Carolina Short", license: "OFL" },
    scripts: ["latin-ext", "greek", "vietnamese"],
    connected: false,
    tune: t({ sizeAdjust: 0.9, weight: 0.7 }),
  },
  {
    id: "pip",
    name: "Pip",
    blurb: "Round, neat and a bit young. Worksheets and kids' notes.",
    category: "print",
    tier: "free",
    font: { dir: "comingsoon", file: "ComingSoon-Regular.ttf", family: "Coming Soon", designer: "Open Window", license: "Apache-2.0" },
    scripts: [],
    connected: false,
    tune: t(),
  },
  {
    id: "sasha",
    name: "Sasha",
    blurb: "Clear, compact print that also writes Cyrillic.",
    category: "print",
    tier: "free",
    font: { dir: "neucha", file: "Neucha.ttf", family: "Neucha", designer: "Jovanny Lemonad", license: "OFL" },
    scripts: ["cyrillic"],
    connected: false,
    tune: t({ weight: 0.6 }),
  },

  /* --------------------- Everyday, unpolished hands --------------------- */
  {
    id: "zoe",
    name: "Zoe",
    blurb: "Loose teenage print with round dots and uneven letters. Nobody's neatest page.",
    category: "casual",
    tier: "free",
    font: { dir: "gloriahallelujah", file: "GloriaHallelujah.ttf", family: "Gloria Hallelujah", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 0.92, weight: 0.8 }),
  },
  {
    id: "max",
    name: "Max",
    blurb: "Chunky school-kid print, pressed hard into the page.",
    category: "casual",
    tier: "free",
    font: { dir: "schoolbell", file: "Schoolbell-Regular.ttf", family: "Schoolbell", designer: "Font Diner", license: "Apache-2.0" },
    scripts: [],
    connected: false,
    tune: t({ weight: 0.5 }),
  },
  {
    id: "lily",
    name: "Lily",
    blurb: "Bubbly and friendly, the hand on half the notebooks in any classroom.",
    category: "casual",
    tier: "free",
    font: { dir: "indieflower", file: "IndieFlower-Regular.ttf", family: "Indie Flower", designer: "Kimberly Geswein", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: false,
    tune: t({ sizeAdjust: 0.95 }),
  },
  {
    id: "rory",
    name: "Rory",
    blurb: "Capitals and lowercase mixed at random. Written in a hurry, and it shows.",
    category: "casual",
    tier: "free",
    font: { dir: "justmeagaindownhere", file: "JustMeAgainDownHere.ttf", family: "Just Me Again Down Here", designer: "Kimberly Geswein", license: "OFL" },
    scripts: ["latin-ext"],
    connected: false,
    tune: t({ sizeAdjust: 1.05, weight: 0.8 }),
  },
  {
    id: "milo",
    name: "Milo",
    blurb: "Wide, round and wobbly, like a kid who has just learnt joined-up letters are optional.",
    category: "casual",
    tier: "free",
    font: { dir: "swankyandmoomoo", file: "SwankyandMooMoo.ttf", family: "Swanky and Moo Moo", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 0.85 }),
  },
  {
    id: "tara",
    name: "Tara",
    blurb: "Thin, loose and slightly lopsided. Everyday notes with no effort to impress.",
    category: "casual",
    tier: "free",
    font: { dir: "chilanka", file: "Chilanka-Regular.ttf", family: "Chilanka", designer: "SMC, Santhosh Thottingal", license: "OFL" },
    scripts: ["latin-ext"],
    connected: false,
    tune: t({ weight: 1.1 }),
  },
  {
    id: "doc",
    name: "Doc",
    blurb: "A cramped, sloppy scrawl. Think prescription pad at the end of a long shift.",
    category: "casual",
    tier: "pro",
    font: { dir: "lovedbytheking", file: "LovedbytheKing.ttf", family: "Loved by the King", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 1.25, weight: 1.1 }),
  },
  {
    id: "remy",
    name: "Remy",
    blurb: "Rough brush-pen strokes, fast and uneven.",
    category: "casual",
    tier: "pro",
    font: { dir: "mansalva", file: "Mansalva-Regular.ttf", family: "Mansalva", designer: "Carolina Short", license: "OFL" },
    scripts: ["latin-ext", "greek", "vietnamese"],
    connected: false,
    tune: t({ weight: 0.2 }),
  },
  {
    id: "bea",
    name: "Bea",
    blurb: "Heavy felt-tip notes, a bit smudgy and very sure of itself.",
    category: "casual",
    tier: "pro",
    font: { dir: "caveatbrush", file: "CaveatBrush-Regular.ttf", family: "Caveat Brush", designer: "Impallari Type", license: "OFL" },
    scripts: ["latin-ext"],
    connected: false,
    tune: t({ weight: 0.2 }),
  },
  {
    id: "oz",
    name: "Oz",
    blurb: "Shaky, hand-drawn outlines. Written on a bus, or with the wrong hand.",
    category: "casual",
    tier: "pro",
    font: { dir: "kranky", file: "Kranky-Regular.ttf", family: "Kranky", designer: "Sideshow", license: "Apache-2.0" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 0.95, weight: 0.6 }),
  },

  /* ------------------------------ Pro ------------------------------- */
  {
    id: "celeste",
    name: "Celeste",
    blurb: "Joined-up cursive with ink-heavy loops. Looks written in one breath.",
    category: "cursive",
    tier: "pro",
    font: { dir: "homemadeapple", file: "HomemadeApple-Regular.ttf", family: "Homemade Apple", designer: "Font Diner", license: "Apache-2.0" },
    scripts: [],
    connected: true,
    tune: t({ sizeAdjust: 0.85, weight: 0.5 }),
  },
  {
    id: "rosa",
    name: "Rosa",
    blurb: "Neat school cursive, the kind taught with a practice book.",
    category: "cursive",
    tier: "pro",
    font: { dir: "cedarvillecursive", file: "Cedarville-Cursive.ttf", family: "Cedarville Cursive", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: true,
    tune: t({ sizeAdjust: 0.95 }),
  },
  {
    id: "elodie",
    name: "Elodie",
    blurb: "Confident, loose print with generous descenders.",
    category: "print",
    tier: "pro",
    font: { dir: "labelleaurore", file: "LaBelleAurore.ttf", family: "La Belle Aurore", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 0.9 }),
  },
  {
    id: "marlowe",
    name: "Marlowe",
    blurb: "Big, looping cursive for letters and cards.",
    category: "cursive",
    tier: "pro",
    font: { dir: "dawningofanewday", file: "DawningofaNewDay.ttf", family: "Dawning of a New Day", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: true,
    tune: t(),
  },
  {
    id: "idris",
    name: "Idris",
    blurb: "Flowing and slightly untidy, like notes taken during a lecture.",
    category: "print",
    tier: "pro",
    font: { dir: "zeyada", file: "Zeyada.ttf", family: "Zeyada", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 1.05 }),
  },
  {
    id: "jonah",
    name: "Jonah",
    blurb: "Chunky felt-tip print with a heavy hand.",
    category: "marker",
    tier: "pro",
    font: { dir: "coveredbyyourgrace", file: "CoveredByYourGrace.ttf", family: "Covered By Your Grace", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ weight: 0.6 }),
  },
  {
    id: "hugo",
    name: "Hugo",
    blurb: "Tall, condensed and fast. Squeezes long answers onto fewer pages.",
    category: "marker",
    tier: "pro",
    font: { dir: "justanotherhand", file: "JustAnotherHand-Regular.ttf", family: "Just Another Hand", designer: "Astigmatic", license: "Apache-2.0" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 1.1, weight: 0.4 }),
  },
  {
    id: "luna",
    name: "Luna",
    blurb: "Thin, bouncy print that never quite sits on the line.",
    category: "print",
    tier: "pro",
    font: { dir: "overtherainbow", file: "OvertheRainbow.ttf", family: "Over the Rainbow", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ weight: 1.1 }),
  },
  {
    id: "ines",
    name: "Ines",
    blurb: "Tall and narrow with a gentle lean.",
    category: "print",
    tier: "pro",
    font: { dir: "sueellenfrancisco", file: "SueEllenFrancisco-Regular.ttf", family: "Sue Ellen Francisco", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t(),
  },
  {
    id: "nika",
    name: "Nika",
    blurb: "Slanted, quick and fluent. Writes Latin and Cyrillic.",
    category: "cursive",
    tier: "pro",
    font: { dir: "badscript", file: "BadScript-Regular.ttf", family: "Bad Script", designer: "Gaslight", license: "OFL" },
    scripts: ["latin-ext", "cyrillic", "vietnamese"],
    connected: false,
    tune: t({ weight: 1.1 }),
  },
  {
    id: "vera",
    name: "Vera",
    blurb: "Calligraphic joined script with a broad-nib feel. Latin and Cyrillic.",
    category: "elegant",
    tier: "pro",
    font: { dir: "marckscript", file: "MarckScript-Regular.ttf", family: "Marck Script", designer: "Denis Masharov", license: "OFL" },
    scripts: ["latin-ext", "cyrillic"],
    connected: true,
    tune: t({ sizeAdjust: 0.88, weight: 0.5 }),
  },
  {
    id: "aiko",
    name: "Aiko",
    blurb: "Light italic, written fast with a fine pen.",
    category: "cursive",
    tier: "pro",
    font: { dir: "ooohbaby", file: "OoohBaby-Regular.ttf", family: "Oooh Baby", designer: "Robert Leuschke", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: false,
    tune: t({ sizeAdjust: 0.95, weight: 1.1 }),
  },
  {
    id: "dre",
    name: "Dre",
    blurb: "Marker lettering with attitude. Posters, titles, sticky notes.",
    category: "marker",
    tier: "pro",
    font: { dir: "sedgwickave", file: "SedgwickAve-Regular.ttf", family: "Sedgwick Ave", designer: "Pedro Vergani, Kevin Burke", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: false,
    tune: t({ sizeAdjust: 1.08, weight: 0.4 }),
  },
  {
    id: "sol",
    name: "Sol",
    blurb: "Thin, spacious print that leaves room to breathe.",
    category: "print",
    tier: "pro",
    font: { dir: "annieuseyourtelescope", file: "AnnieUseYourTelescope-Regular.ttf", family: "Annie Use Your Telescope", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ weight: 1.1 }),
  },
  {
    id: "poppy",
    name: "Poppy",
    blurb: "Loose, sprawling and friendly. Diary pages and letters to friends.",
    category: "print",
    tier: "pro",
    font: { dir: "thegirlnextdoor", file: "TheGirlNextDoor.ttf", family: "The Girl Next Door", designer: "Kimberly Geswein", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ weight: 1.1 }),
  },
  {
    id: "tomas",
    name: "Tomas",
    blurb: "Natural italic with a steady rhythm.",
    category: "cursive",
    tier: "pro",
    font: { dir: "grapenuts", file: "GrapeNuts-Regular.ttf", family: "Grape Nuts", designer: "Robert Leuschke", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: false,
    tune: t({ sizeAdjust: 0.9 }),
  },
  {
    id: "jin",
    name: "Jin",
    blurb: "Quick pen strokes, compact and even.",
    category: "print",
    tier: "pro",
    font: { dir: "nanumpenscript", file: "NanumPenScript-Latin.ttf", family: "Nanum Pen Script", designer: "Sandoll Communication", license: "OFL" },
    scripts: [],
    connected: false,
    tune: t({ sizeAdjust: 1.1, weight: 0.5 }),
  },
  {
    id: "vivian",
    name: "Vivian",
    blurb: "Flourished capitals and a formal slant. Invitations and thank-you cards.",
    category: "elegant",
    tier: "pro",
    font: { dir: "loversquarrel", file: "LoversQuarrel-Regular.ttf", family: "Lovers Quarrel", designer: "Robert Leuschke", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: true,
    tune: t(),
  },
  {
    id: "grace",
    name: "Grace",
    blurb: "Refined joined cursive with long, thin connecting strokes.",
    category: "elegant",
    tier: "pro",
    font: { dir: "whisper", file: "Whisper-Regular.ttf", family: "Whisper", designer: "Robert Leuschke", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: true,
    tune: t(),
  },
  {
    id: "leo",
    name: "Leo",
    blurb: "Condensed italic, quick and a little dramatic.",
    category: "cursive",
    tier: "pro",
    font: { dir: "licorice", file: "Licorice-Regular.ttf", family: "Licorice", designer: "Robert Leuschke", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: false,
    tune: t(),
  },
  {
    id: "amara",
    name: "Amara",
    blurb: "Tall, thin and elegant with long descenders.",
    category: "elegant",
    tier: "pro",
    font: { dir: "shalimar", file: "Shalimar-Regular.ttf", family: "Shalimar", designer: "Robert Leuschke", license: "OFL" },
    scripts: ["latin-ext", "vietnamese"],
    connected: false,
    tune: t(),
  },
];

export const styleById = (id: string) => STYLES.find((s) => s.id === id);
export const DEFAULT_STYLE_ID = "mira";
