import { FileSpreadsheet } from "lucide-react";
import { Section } from "@/components/Section";
import { ButtonLink } from "@/components/ui/Button";
import s from "./home.module.css";

/** Batch letters for businesses. */
export function Business() {
  return (
    <Section tone="page">
      <div className={s.business}>
        <div>
          <p className={s.kicker}>Truehand for business</p>
          <h2 className={s.businessTitle}>Hundreds of handwritten letters from one spreadsheet</h2>
          <p className={s.businessText}>
            Write a template once, with fields like <code>{"{{first_name}}"}</code>, upload a CSV, and download one handwritten letter, note or envelope per
            row. Transparent PNGs drop straight into print designs.
          </p>
          <div className={s.row}>
            <ButtonLink href="/business">For business</ButtonLink>
            <ButtonLink href="/batch" variant="secondary">
              <FileSpreadsheet aria-hidden="true" />
              Try batch letters
            </ButtonLink>
          </div>
        </div>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          className={s.businessImg}
          src="/specimens/use-letters.webp"
          alt="A handwritten thank-you letter generated by Truehand."
          width={794}
          height={617}
          loading="lazy"
        />
      </div>
    </Section>
  );
}
